services:
  cascade:
    restart: always
    container_name: cascade
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "360:80"   # Map external port 200 to container's port 80
    networks:
      - shared
networks:
  shared:
    name: shared
    external: true
